---
- hosts: tailscale-endpoints            # Host group for your endpoints
  vars:
    token: your_token_here              # Your NRDP token.
    nrdp-endpoint: your_endpoint_here   # Your NRDP endpoint. Just include the hostname or IP (No http:// or /nrdp)
    scripts-remote-dir: /usr/local/     # If you want send_nrdp.sh and tailscale-heartbeat.sh to live somewhere else, change this. Include the trailing slash.
    script-owner: username              # Who is going to own the scripts and run the cron job.
    interval: 5                         # Interval in minutes to run the heartbeat script
  tasks:
    - name: Copy tailscale-heartbeat.sh to remote host
      ansible.builtin.template:
        src: templates/tailscale-heartbeat.sh.j2
        dest: {{ scripts-remote-dir }}tailscale-heartbeat.sh    
        owner: {{ script-owner }}
    
    - name: Copy send_nrdp.sh to remote host
      ansible.builtin.template:
        src: files/send_nrdp.sh
        dest: {{ scripts-remote-dir}}send_nrdp.sh
        owner: {{ script-owner }}
    
    - name: Create cronjob to run tailscale-heartbeat.sh 
      ansible.builtin.cron:
        name: "Report Tailscale status to Nagios"
        minute: /5
        job: {{ scripts-remote-dir }}tailscale-heartbeat.sh